# Generated by Django 3.0.7 on 2020-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Student Name')),
                ('age', models.PositiveIntegerField(default=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=8)),
                ('picture', models.ImageField(upload_to='media/')),
                ('fees', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
