# Generated by Django 3.0.7 on 2020-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
